/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2021-05-13 23:41:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, shrink-to-fit=no\">\r\n");
      out.write("    <title>Proyecto_final</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Bitter:400,700\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/fonts/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/fonts/ionicons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Article-List.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Features-Boxed.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Footer-Dark.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Header-Blue.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Header-Dark.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Highlight-Phone.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/Navigation-with-Button.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"opacity: 1;filter: blur(0px);\">\r\n");
      out.write("    <nav class=\"navbar navbar-light navbar-expand-md sticky-top navigation-clean-button\" data-aos=\"fade\" style=\"filter: blur(0px);opacity: 0.90;\">\r\n");
      out.write("        <div class=\"container-fluid\"><a class=\"navbar-brand\" href=\"#\"><img src=\"assets/img/Main%20logo.png\" style=\"width: 149px;margin: 9px;\"></a><button data-toggle=\"collapse\" class=\"navbar-toggler\" data-target=\"#navcol-1\"><span class=\"sr-only\">Toggle navigation</span><span class=\"navbar-toggler-icon\"></span></button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse justify-content-end\" id=\"navcol-1\"><span class=\"navbar-text actions\"> <a class=\"login\" href=\"login.jsp\">Iniciar sesión</a><a class=\"btn btn-light action-button\" role=\"button\" data-bss-hover-animate=\"pulse\" href=\"register.jsp\" style=\"background: #ffdf08;color: rgb(0,0,0);\">Registrarse</a><a class=\"login\" href=\"#\" style=\"margin-left: 15px;\">EUR</a></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <section data-aos=\"fade\" class=\"highlight-phone\" style=\"background: rgb(42,7,110);height: 380px;\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-8\" style=\"margin-top: 25px;\">\r\n");
      out.write("                    <div class=\"intro\">\r\n");
      out.write("                        <h2 style=\"color: var(--light);\">EL EXCHANGE DE CONFIANZA </h2>\r\n");
      out.write("                        <p style=\"color: var(--light);\">En CriCoin te damos el cambio más justo. Somos lideres del sector. &nbsp;</p><input type=\"email\" style=\"border-radius: 5px;margin-right: 13px;margin-bottom: 10px;\"><a class=\"btn btn-primary\" role=\"button\" href=\"register.jsp\" style=\"background: #ffdf08;border-radius: 15px;color: var(--gray-dark);\">Registrarse</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-4\">\r\n");
      out.write("                    <div class=\"d-none d-md-block phone-mockup\"><img class=\"device\" src=\"assets/img/bitcoin-4851376_1280.png\" style=\"margin: 0px;box-shadow: 0px 0px 20px;margin-top: 25px;\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section data-aos=\"fade\" style=\"margin-top: 43px;margin-bottom: 56px;\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-3 col-sm-6 mt-4\"><a href=\"#\"><img data-bss-hover-animate=\"pulse\" src=\"assets/img/bitcoin-3132574_640.jpg\" style=\"width: 100%;height: auto;box-shadow: 0px 0px 20px rgb(152,152,153);border-radius: 5px;\"></a></div>\r\n");
      out.write("                <div class=\"col-lg-3 col-sm-6 mt-4\"><a href=\"#\"><img data-bss-hover-animate=\"pulse\" src=\"assets/img/bitcoin-1813503_640.jpg\" style=\"width: 100%;height: auto;box-shadow: 0px 0px 20px var(--secondary);border-radius: 5px;\"></a></div>\r\n");
      out.write("                <div class=\"col-lg-3 col-sm-6 mt-4\"><a href=\"#\"><img data-bss-hover-animate=\"pulse\" src=\"assets/img/crypto-3569795_640.jpg\" style=\"width: 100%;height: auto;box-shadow: 0px 0px 20px var(--secondary);border-radius: 5px;\"></a></div>\r\n");
      out.write("                <div class=\"col-lg-3 col-sm-6 mt-4\"><a href=\"#\"><img data-bss-hover-animate=\"pulse\" src=\"assets/img/analytics-3088958_640.jpg\" style=\"background-size: cover;width: 100%;height: auto;box-shadow: 0px 0px 20px var(--secondary);border-radius: 5px;\"></a></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section style=\"margin-top: 43px;margin-bottom: 56px;\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-3 col-sm-6 mt-4\"><a href=\"#\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-body shadow\" data-aos=\"fade\" style=\"color: rgb(0,0,0);border-radius: 5px;\">\r\n");
      out.write("                                <h4 class=\"card-title\" style=\"color: #000000;\"><i class=\"fa fa-bitcoin\" style=\"color: #ffdf08;\"></i>&nbsp;BNB/EUR</h4>\r\n");
      out.write("                                <p class=\"card-text\" style=\"color: rgb(0, 0, 0);\">Nullam id dolor id nibh ultricies vehicula ut id elit.</p><a class=\"card-link\" href=\"#\"><i class=\"fa fa-arrow-circle-right\" style=\"color: #ffdf08;\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a></div>\r\n");
      out.write("                <div class=\"col-lg-3 col-sm-6 mt-4\"><a href=\"#\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-body shadow\" data-aos=\"fade\" style=\"color: rgb(0,0,0);border-radius: 5px;\">\r\n");
      out.write("                                <h4 class=\"card-title\" style=\"color: #000000;\"><i class=\"fa fa-bitcoin\" style=\"color: #ffdf08;\"></i>&nbsp;BNB/EUR</h4>\r\n");
      out.write("                                <p class=\"card-text\" style=\"color: rgb(0, 0, 0);\">Nullam id dolor id nibh ultricies vehicula ut id elit.</p><a class=\"card-link\" href=\"#\"><i class=\"fa fa-arrow-circle-right\" style=\"color: #ffdf08;\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a></div>\r\n");
      out.write("                <div class=\"col-lg-3 col-sm-6 mt-4\"><a href=\"#\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-body shadow\" data-aos=\"fade\" style=\"color: rgb(0,0,0);border-radius: 5px;\">\r\n");
      out.write("                                <h4 class=\"card-title\" style=\"color: #000000;\"><i class=\"fa fa-bitcoin\" style=\"color: #ffdf08;\"></i>&nbsp;BNB/EUR</h4>\r\n");
      out.write("                                <p class=\"card-text\" style=\"color: rgb(0, 0, 0);\">Nullam id dolor id nibh ultricies vehicula ut id elit.</p><a class=\"card-link\" href=\"#\"><i class=\"fa fa-arrow-circle-right\" style=\"color: #ffdf08;\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a></div>\r\n");
      out.write("                <div class=\"col-lg-3 col-sm-6 mt-4\"><a href=\"#\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-body shadow\" data-aos=\"fade\" style=\"color: rgb(0,0,0);border-radius: 5px;\">\r\n");
      out.write("                                <h4 class=\"card-title\" style=\"color: #000000;\"><i class=\"fa fa-bitcoin\" style=\"color: #ffdf08;\"></i>&nbsp;BNB/EUR</h4>\r\n");
      out.write("                                <p class=\"card-text\" style=\"color: rgb(0, 0, 0);\">Nullam id dolor id nibh ultricies vehicula ut id elit.</p><a class=\"card-link\" href=\"#\"><i class=\"fa fa-arrow-circle-right\" style=\"color: #ffdf08;\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </a></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section data-aos=\"fade\" class=\"article-list\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"intro\">\r\n");
      out.write("                <h2 class=\"text-center\" style=\"margin-bottom: 7px;padding: 22px 0px 0px;\">Academia</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row articles\">\r\n");
      out.write("                <div class=\"col-sm-6 col-md-4 item\"><a href=\"#\"><img class=\"img-fluid shadow\" src=\"assets/img/chart-2779132_640.jpg\" style=\"border-radius: 5px;\"></a>\r\n");
      out.write("                    <h3 class=\"name\">Aprende a tradear</h3>\r\n");
      out.write("                    <p class=\"description\">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, interdum justo suscipit id.</p><a class=\"action\" href=\"#\"><i class=\"fa fa-arrow-circle-right\" style=\"color: #ffdf08;\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-6 col-md-4 item\"><a href=\"#\"><img class=\"img-fluid shadow\" src=\"assets/img/stock-1863880_640.jpg\" style=\"border-radius: 5px;\"></a>\r\n");
      out.write("                    <h3 class=\"name\">Aprende BlockChain </h3>\r\n");
      out.write("                    <p class=\"description\">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, interdum justo suscipit id.</p><a class=\"action\" href=\"#\"><i class=\"fa fa-arrow-circle-right\" style=\"color: #ffdf08;\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-6 col-md-4 item\"><a href=\"#\"><img class=\"img-fluid shadow\" src=\"assets/img/mathematics-3821034_640.jpg\" style=\"border-radius: 5px;\"></a>\r\n");
      out.write("                    <h3 class=\"name\">¿Cómo funciona CriCoin?</h3>\r\n");
      out.write("                    <p class=\"description\">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, interdum justo suscipit id.</p><a class=\"action\" href=\"#\"><i class=\"fa fa-arrow-circle-right\" style=\"color: #ffdf08;\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <footer class=\"footer-dark\" style=\"background: #2a076e;\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-6 col-md-3 item\">\r\n");
      out.write("                    <h3 style=\"color: #ffffff;\">Servicios</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">Web design</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Development</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Hosting</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-6 col-md-3 item\">\r\n");
      out.write("                    <h3 style=\"color: #ffffff;\">About</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\" style=\"color: rgb(240, 249, 255);\">Company</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Team</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Careers</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 item text\">\r\n");
      out.write("                    <h3 style=\"color: #ffffff;\"><i class=\"fa fa-rocket\"></i>&nbsp;CriCoin</h3>\r\n");
      out.write("                    <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col item social\"><a href=\"#\" style=\"color: #ffdf08;\"><i class=\"icon ion-social-facebook\"></i></a><a href=\"#\" style=\"color: #ffdf08;\"><i class=\"icon ion-social-twitter\"></i></a><a href=\"#\" style=\"color: #ffdf08;\"><i class=\"icon ion-social-snapchat\"></i></a><a href=\"#\" style=\"color: #ffdf08;\"><i class=\"icon ion-social-instagram\"></i></a></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <p class=\"copyright\"><i class=\"fa fa-rocket\"></i>&nbsp;CriCoin © 2021</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/bs-init.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
